export const SHOW_DELETE_MOVIE_MODAL = 'SHOW_DELETE_MOVIE_MODAL'
export const SHOW_EDIT_MOVIE_MODAL = 'SHOW_EDIT_MOVIE_MODAL'
export const SHOW_ADD_MOVIE_MODAL = 'SHOW_ADD_MOVIE_MODAL'

export const HIDE_EDIT_MOVIE_DATA_MODAL = 'HIDE_EDIT_MOVIE_DATA_MODAL'
export const HIDE_ADD_MOVIE_MODAL = 'HIDE_ADD_MOVIE_MODAL'
export const HIDE_DELETE_MOVIE_MODAL = 'HIDE_DELETE_MOVIE_MODAL'

export const MOVIE_DELETE_MODAL = 'MOVIE_DELETE_MODAL'
export const MOVIE_EDIT_MODAL = 'MOVIE_EDIT_MODAL'
export const MOVIE_ADD_MODAL = 'MOVIE_ADD_MODAL'
