export const SHOW_DELETE_MOVIE_MODAL = 'SHOW_DELETE_MOVIE_MODAL'
export const HIDE_DELETE_MOVIE_MODAL = 'HIDE_DELETE_MOVIE_MODAL'

export const MOVIE_DELETE_MODAL = 'MOVIE_DELETE_MODAL'
// export const MODAL_NAME = 'MOVIE_DELETE_MODAL'
