export const GET_MOVIES = 'GET_MOVIES'
export const GET_MOVIES_COMPLETED = 'GET_MOVIES_COMPLETED'
export const GET_MOVIES_REJECTED = 'GET_MOVIES_REJECTED'

export const ADD_MOVIE = 'ADD_MOVIE'
export const ADD_MOVIE_COMPLETED = 'ADD_MOVIE_COMPLETED'
export const ADD_MOVIE_REJECTED = 'ADD_MOVIE_REJECTED'

export const EDIT_MOVIE = 'EDIT_MOVIE'

export const DELETE_MOVIE = 'DELETE_MOVIE'
export const DELETE_MOVIE_COMPLETED = 'DELETE_MOVIE_COMPLETED'
export const DELETE_MOVIE_REJECTED = 'DELETE_MOVIE_REJECTED'
